config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  controller :home do
    get :convert
    get :pdf
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def pdf
  end

  def convert
  	_url = request.base_url + pdf_path
  	_pdf = Dhalang::PDF.get_from_url(_url)
  	_file_name = "Report" 
    File.open("#{Rails.root}/public/#{_file_name}.pdf", "w+b") << _pdf
	  redirect_to "/#{_file_name}.pdf"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class=""style="padding:30 px; margin: auto; text-align: center;">
    <%= link_to "CONVERT TO PDF", convert_path, target: "_blank" %>
</div>
<canvas id="sample"></canvas>
<script type="text/javascript">
    <%= render "home/partials/main.js" %>
</script>

app/views/home/partials/_main.js.erb
var MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
var config = {
	type: 'line',
	data: {
		labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
		datasets: [{
			label: 'My First dataset',
			borderColor: "#C6C22F",
			backgroundColor: "#C6C22F",
			data: [
				44,
				55,
				20,
				21,
				89,
				52,
				33
			],
		}, {
			label: 'My Second dataset',
			borderColor: "#4DAA33",
			backgroundColor: "#4DAA33",
			data: [
				24,
				55,
				60,
				11,
				89,
				82,
				73
			],
		}, {
			label: 'My Third dataset',
			borderColor: "#C559A5",
			backgroundColor: "#C559A5",
			data: [
				41,
				55,
				94,
				61,
				81,
				52,
				30
			],
		}, {
			label: 'My Third dataset',
			borderColor: "#45CCB7",
			backgroundColor: "#45CCB7",
			data: [
				23,77,58,43,45,75,32
			],
		}]
	},
	options: {
		responsive: true,
		title: {
			display: true,
			text: 'Chart.js Line Chart - Stacked Area'
		},
		tooltips: {
			mode: 'index',
		},
		hover: {
			mode: 'index'
		},
		scales: {
			xAxes: [{
				scaleLabel: {
					display: true,
					labelString: 'Month'
				}
			}],
			yAxes: [{
				stacked: true,
				scaleLabel: {
					display: true,
					labelString: 'Value'
				}
			}]
		}
	}
};

window.onload = function() {
	var ctx = document.getElementById('sample').getContext('2d');
	window.myLine = new Chart(ctx, config);
};

app/views/home/pdf.html.erb
<canvas id="sample"></canvas>

<script type="text/javascript">
	<%= render "home/partials/main.js"%>
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chartdemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>